// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXb0B5bJpXzHhBjtnRkjDgQXeiJffItpM',
    appId: '1:209613231833:web:1f0fd73d5d395f94ed50c8',
    messagingSenderId: '209613231833',
    projectId: 'prepswipe-6fdf0',
    authDomain: 'prepswipe-6fdf0.firebaseapp.com',
    storageBucket: 'prepswipe-6fdf0.firebasestorage.app',
    measurementId: 'G-WHCYE1R8CV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsXIFSIPR3feeSxPzcQ_3IzJhGlduEU68',
    appId: '1:209613231833:android:a273e9d84f929188ed50c8',
    messagingSenderId: '209613231833',
    projectId: 'prepswipe-6fdf0',
    storageBucket: 'prepswipe-6fdf0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhszF7ynBVZsA2Wn2kn9dl1BJZ_xaXkxk',
    appId: '1:209613231833:ios:19c55b80e3910465ed50c8',
    messagingSenderId: '209613231833',
    projectId: 'prepswipe-6fdf0',
    storageBucket: 'prepswipe-6fdf0.firebasestorage.app',
    androidClientId: '209613231833-3f3pueb8k3lgcl8j4c1k39rl1ilkb36k.apps.googleusercontent.com',
    iosClientId: '209613231833-did45hd4dgmg59ossol50eudb591slj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.prepswipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhszF7ynBVZsA2Wn2kn9dl1BJZ_xaXkxk',
    appId: '1:209613231833:ios:19c55b80e3910465ed50c8',
    messagingSenderId: '209613231833',
    projectId: 'prepswipe-6fdf0',
    storageBucket: 'prepswipe-6fdf0.firebasestorage.app',
    androidClientId: '209613231833-3f3pueb8k3lgcl8j4c1k39rl1ilkb36k.apps.googleusercontent.com',
    iosClientId: '209613231833-did45hd4dgmg59ossol50eudb591slj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.prepswipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXb0B5bJpXzHhBjtnRkjDgQXeiJffItpM',
    appId: '1:209613231833:web:d77146c656e5d604ed50c8',
    messagingSenderId: '209613231833',
    projectId: 'prepswipe-6fdf0',
    authDomain: 'prepswipe-6fdf0.firebaseapp.com',
    storageBucket: 'prepswipe-6fdf0.firebasestorage.app',
    measurementId: 'G-C6S026BJKS',
  );
}
